///
//  Generated code. Do not modify.
//  source: google/ads/googleads/v1/enums/feed_item_quality_disapproval_reason.proto
///
// ignore_for_file: camel_case_types,non_constant_identifier_names,library_prefixes,unused_import,unused_shown_name

// ignore_for_file: UNDEFINED_SHOWN_NAME,UNUSED_SHOWN_NAME
import 'dart:core' as $core show int, dynamic, String, List, Map;
import 'package:protobuf/protobuf.dart' as $pb;

class FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason extends $pb.ProtobufEnum {
  static const FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason UNSPECIFIED = FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason._(0, 'UNSPECIFIED');
  static const FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason UNKNOWN = FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason._(1, 'UNKNOWN');
  static const FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason PRICE_TABLE_REPETITIVE_HEADERS = FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason._(2, 'PRICE_TABLE_REPETITIVE_HEADERS');
  static const FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason PRICE_TABLE_REPETITIVE_DESCRIPTION = FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason._(3, 'PRICE_TABLE_REPETITIVE_DESCRIPTION');
  static const FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason PRICE_TABLE_INCONSISTENT_ROWS = FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason._(4, 'PRICE_TABLE_INCONSISTENT_ROWS');
  static const FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason PRICE_DESCRIPTION_HAS_PRICE_QUALIFIERS = FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason._(5, 'PRICE_DESCRIPTION_HAS_PRICE_QUALIFIERS');
  static const FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason PRICE_UNSUPPORTED_LANGUAGE = FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason._(6, 'PRICE_UNSUPPORTED_LANGUAGE');
  static const FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason PRICE_TABLE_ROW_HEADER_TABLE_TYPE_MISMATCH = FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason._(7, 'PRICE_TABLE_ROW_HEADER_TABLE_TYPE_MISMATCH');
  static const FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason PRICE_TABLE_ROW_HEADER_HAS_PROMOTIONAL_TEXT = FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason._(8, 'PRICE_TABLE_ROW_HEADER_HAS_PROMOTIONAL_TEXT');
  static const FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason PRICE_TABLE_ROW_DESCRIPTION_NOT_RELEVANT = FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason._(9, 'PRICE_TABLE_ROW_DESCRIPTION_NOT_RELEVANT');
  static const FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason PRICE_TABLE_ROW_DESCRIPTION_HAS_PROMOTIONAL_TEXT = FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason._(10, 'PRICE_TABLE_ROW_DESCRIPTION_HAS_PROMOTIONAL_TEXT');
  static const FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason PRICE_TABLE_ROW_HEADER_DESCRIPTION_REPETITIVE = FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason._(11, 'PRICE_TABLE_ROW_HEADER_DESCRIPTION_REPETITIVE');
  static const FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason PRICE_TABLE_ROW_UNRATEABLE = FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason._(12, 'PRICE_TABLE_ROW_UNRATEABLE');
  static const FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason PRICE_TABLE_ROW_PRICE_INVALID = FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason._(13, 'PRICE_TABLE_ROW_PRICE_INVALID');
  static const FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason PRICE_TABLE_ROW_URL_INVALID = FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason._(14, 'PRICE_TABLE_ROW_URL_INVALID');
  static const FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason PRICE_HEADER_OR_DESCRIPTION_HAS_PRICE = FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason._(15, 'PRICE_HEADER_OR_DESCRIPTION_HAS_PRICE');
  static const FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason STRUCTURED_SNIPPETS_HEADER_POLICY_VIOLATED = FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason._(16, 'STRUCTURED_SNIPPETS_HEADER_POLICY_VIOLATED');
  static const FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason STRUCTURED_SNIPPETS_REPEATED_VALUES = FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason._(17, 'STRUCTURED_SNIPPETS_REPEATED_VALUES');
  static const FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason STRUCTURED_SNIPPETS_EDITORIAL_GUIDELINES = FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason._(18, 'STRUCTURED_SNIPPETS_EDITORIAL_GUIDELINES');
  static const FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason STRUCTURED_SNIPPETS_HAS_PROMOTIONAL_TEXT = FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason._(19, 'STRUCTURED_SNIPPETS_HAS_PROMOTIONAL_TEXT');

  static const $core.List<FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason> values = <FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason> [
    UNSPECIFIED,
    UNKNOWN,
    PRICE_TABLE_REPETITIVE_HEADERS,
    PRICE_TABLE_REPETITIVE_DESCRIPTION,
    PRICE_TABLE_INCONSISTENT_ROWS,
    PRICE_DESCRIPTION_HAS_PRICE_QUALIFIERS,
    PRICE_UNSUPPORTED_LANGUAGE,
    PRICE_TABLE_ROW_HEADER_TABLE_TYPE_MISMATCH,
    PRICE_TABLE_ROW_HEADER_HAS_PROMOTIONAL_TEXT,
    PRICE_TABLE_ROW_DESCRIPTION_NOT_RELEVANT,
    PRICE_TABLE_ROW_DESCRIPTION_HAS_PROMOTIONAL_TEXT,
    PRICE_TABLE_ROW_HEADER_DESCRIPTION_REPETITIVE,
    PRICE_TABLE_ROW_UNRATEABLE,
    PRICE_TABLE_ROW_PRICE_INVALID,
    PRICE_TABLE_ROW_URL_INVALID,
    PRICE_HEADER_OR_DESCRIPTION_HAS_PRICE,
    STRUCTURED_SNIPPETS_HEADER_POLICY_VIOLATED,
    STRUCTURED_SNIPPETS_REPEATED_VALUES,
    STRUCTURED_SNIPPETS_EDITORIAL_GUIDELINES,
    STRUCTURED_SNIPPETS_HAS_PROMOTIONAL_TEXT,
  ];

  static final $core.Map<$core.int, FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason> _byValue = $pb.ProtobufEnum.initByValue(values);
  static FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason valueOf($core.int value) => _byValue[value];

  const FeedItemQualityDisapprovalReasonEnum_FeedItemQualityDisapprovalReason._($core.int v, $core.String n) : super(v, n);
}

