///
//  Generated code. Do not modify.
//  source: google/ads/googleads/v1/common/metrics.proto
///
// ignore_for_file: camel_case_types,non_constant_identifier_names,library_prefixes,unused_import,unused_shown_name

const Metrics$json = const {
  '1': 'Metrics',
  '2': const [
    const {'1': 'absolute_top_impression_percentage', '3': 95, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'absoluteTopImpressionPercentage'},
    const {'1': 'active_view_cpm', '3': 1, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'activeViewCpm'},
    const {'1': 'active_view_ctr', '3': 79, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'activeViewCtr'},
    const {'1': 'active_view_impressions', '3': 2, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'activeViewImpressions'},
    const {'1': 'active_view_measurability', '3': 96, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'activeViewMeasurability'},
    const {'1': 'active_view_measurable_cost_micros', '3': 3, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'activeViewMeasurableCostMicros'},
    const {'1': 'active_view_measurable_impressions', '3': 4, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'activeViewMeasurableImpressions'},
    const {'1': 'active_view_viewability', '3': 97, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'activeViewViewability'},
    const {'1': 'all_conversions_from_interactions_rate', '3': 65, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'allConversionsFromInteractionsRate'},
    const {'1': 'all_conversions_value', '3': 66, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'allConversionsValue'},
    const {'1': 'all_conversions', '3': 7, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'allConversions'},
    const {'1': 'all_conversions_value_per_cost', '3': 62, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'allConversionsValuePerCost'},
    const {'1': 'all_conversions_from_click_to_call', '3': 118, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'allConversionsFromClickToCall'},
    const {'1': 'all_conversions_from_directions', '3': 119, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'allConversionsFromDirections'},
    const {'1': 'all_conversions_from_interactions_value_per_interaction', '3': 67, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'allConversionsFromInteractionsValuePerInteraction'},
    const {'1': 'all_conversions_from_menu', '3': 120, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'allConversionsFromMenu'},
    const {'1': 'all_conversions_from_order', '3': 121, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'allConversionsFromOrder'},
    const {'1': 'all_conversions_from_other_engagement', '3': 122, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'allConversionsFromOtherEngagement'},
    const {'1': 'all_conversions_from_store_visit', '3': 123, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'allConversionsFromStoreVisit'},
    const {'1': 'all_conversions_from_store_website', '3': 124, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'allConversionsFromStoreWebsite'},
    const {'1': 'average_cost', '3': 8, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'averageCost'},
    const {'1': 'average_cpc', '3': 9, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'averageCpc'},
    const {'1': 'average_cpe', '3': 98, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'averageCpe'},
    const {'1': 'average_cpm', '3': 10, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'averageCpm'},
    const {'1': 'average_cpv', '3': 11, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'averageCpv'},
    const {'1': 'average_frequency', '3': 12, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'averageFrequency'},
    const {'1': 'average_page_views', '3': 99, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'averagePageViews'},
    const {'1': 'average_position', '3': 13, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'averagePosition'},
    const {'1': 'average_time_on_site', '3': 84, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'averageTimeOnSite'},
    const {'1': 'benchmark_average_max_cpc', '3': 14, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'benchmarkAverageMaxCpc'},
    const {'1': 'benchmark_ctr', '3': 77, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'benchmarkCtr'},
    const {'1': 'bounce_rate', '3': 15, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'bounceRate'},
    const {'1': 'clicks', '3': 19, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'clicks'},
    const {'1': 'combined_clicks', '3': 115, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'combinedClicks'},
    const {'1': 'combined_clicks_per_query', '3': 116, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'combinedClicksPerQuery'},
    const {'1': 'combined_queries', '3': 117, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'combinedQueries'},
    const {'1': 'content_budget_lost_impression_share', '3': 20, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'contentBudgetLostImpressionShare'},
    const {'1': 'content_impression_share', '3': 21, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'contentImpressionShare'},
    const {'1': 'conversion_last_received_request_date_time', '3': 73, '4': 1, '5': 11, '6': '.google.protobuf.StringValue', '10': 'conversionLastReceivedRequestDateTime'},
    const {'1': 'conversion_last_conversion_date', '3': 74, '4': 1, '5': 11, '6': '.google.protobuf.StringValue', '10': 'conversionLastConversionDate'},
    const {'1': 'content_rank_lost_impression_share', '3': 22, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'contentRankLostImpressionShare'},
    const {'1': 'conversions_from_interactions_rate', '3': 69, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'conversionsFromInteractionsRate'},
    const {'1': 'conversions_value', '3': 70, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'conversionsValue'},
    const {'1': 'conversions_value_per_cost', '3': 71, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'conversionsValuePerCost'},
    const {'1': 'conversions_from_interactions_value_per_interaction', '3': 72, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'conversionsFromInteractionsValuePerInteraction'},
    const {'1': 'conversions', '3': 25, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'conversions'},
    const {'1': 'cost_micros', '3': 26, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'costMicros'},
    const {'1': 'cost_per_all_conversions', '3': 68, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'costPerAllConversions'},
    const {'1': 'cost_per_conversion', '3': 28, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'costPerConversion'},
    const {'1': 'cost_per_current_model_attributed_conversion', '3': 106, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'costPerCurrentModelAttributedConversion'},
    const {'1': 'cross_device_conversions', '3': 29, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'crossDeviceConversions'},
    const {'1': 'ctr', '3': 30, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'ctr'},
    const {'1': 'current_model_attributed_conversions', '3': 101, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'currentModelAttributedConversions'},
    const {'1': 'current_model_attributed_conversions_from_interactions_rate', '3': 102, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'currentModelAttributedConversionsFromInteractionsRate'},
    const {'1': 'current_model_attributed_conversions_from_interactions_value_per_interaction', '3': 103, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'currentModelAttributedConversionsFromInteractionsValuePerInteraction'},
    const {'1': 'current_model_attributed_conversions_value', '3': 104, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'currentModelAttributedConversionsValue'},
    const {'1': 'current_model_attributed_conversions_value_per_cost', '3': 105, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'currentModelAttributedConversionsValuePerCost'},
    const {'1': 'engagement_rate', '3': 31, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'engagementRate'},
    const {'1': 'engagements', '3': 32, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'engagements'},
    const {'1': 'hotel_average_lead_value_micros', '3': 75, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'hotelAverageLeadValueMicros'},
    const {'1': 'historical_creative_quality_score', '3': 80, '4': 1, '5': 14, '6': '.google.ads.googleads.v1.enums.QualityScoreBucketEnum.QualityScoreBucket', '10': 'historicalCreativeQualityScore'},
    const {'1': 'historical_landing_page_quality_score', '3': 81, '4': 1, '5': 14, '6': '.google.ads.googleads.v1.enums.QualityScoreBucketEnum.QualityScoreBucket', '10': 'historicalLandingPageQualityScore'},
    const {'1': 'historical_quality_score', '3': 82, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'historicalQualityScore'},
    const {'1': 'historical_search_predicted_ctr', '3': 83, '4': 1, '5': 14, '6': '.google.ads.googleads.v1.enums.QualityScoreBucketEnum.QualityScoreBucket', '10': 'historicalSearchPredictedCtr'},
    const {'1': 'gmail_forwards', '3': 85, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'gmailForwards'},
    const {'1': 'gmail_saves', '3': 86, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'gmailSaves'},
    const {'1': 'gmail_secondary_clicks', '3': 87, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'gmailSecondaryClicks'},
    const {'1': 'impression_reach', '3': 36, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'impressionReach'},
    const {'1': 'impressions_from_store_reach', '3': 125, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'impressionsFromStoreReach'},
    const {'1': 'impressions', '3': 37, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'impressions'},
    const {'1': 'interaction_rate', '3': 38, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'interactionRate'},
    const {'1': 'interactions', '3': 39, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'interactions'},
    const {'1': 'interaction_event_types', '3': 100, '4': 3, '5': 14, '6': '.google.ads.googleads.v1.enums.InteractionEventTypeEnum.InteractionEventType', '10': 'interactionEventTypes'},
    const {'1': 'invalid_click_rate', '3': 40, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'invalidClickRate'},
    const {'1': 'invalid_clicks', '3': 41, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'invalidClicks'},
    const {'1': 'mobile_friendly_clicks_percentage', '3': 109, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'mobileFriendlyClicksPercentage'},
    const {'1': 'organic_clicks', '3': 110, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'organicClicks'},
    const {'1': 'organic_clicks_per_query', '3': 111, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'organicClicksPerQuery'},
    const {'1': 'organic_impressions', '3': 112, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'organicImpressions'},
    const {'1': 'organic_impressions_per_query', '3': 113, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'organicImpressionsPerQuery'},
    const {'1': 'organic_queries', '3': 114, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'organicQueries'},
    const {'1': 'percent_new_visitors', '3': 42, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'percentNewVisitors'},
    const {'1': 'phone_calls', '3': 43, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'phoneCalls'},
    const {'1': 'phone_impressions', '3': 44, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'phoneImpressions'},
    const {'1': 'phone_through_rate', '3': 45, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'phoneThroughRate'},
    const {'1': 'relative_ctr', '3': 46, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'relativeCtr'},
    const {'1': 'search_absolute_top_impression_share', '3': 78, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'searchAbsoluteTopImpressionShare'},
    const {'1': 'search_budget_lost_absolute_top_impression_share', '3': 88, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'searchBudgetLostAbsoluteTopImpressionShare'},
    const {'1': 'search_budget_lost_impression_share', '3': 47, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'searchBudgetLostImpressionShare'},
    const {'1': 'search_budget_lost_top_impression_share', '3': 89, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'searchBudgetLostTopImpressionShare'},
    const {'1': 'search_click_share', '3': 48, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'searchClickShare'},
    const {'1': 'search_exact_match_impression_share', '3': 49, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'searchExactMatchImpressionShare'},
    const {'1': 'search_impression_share', '3': 50, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'searchImpressionShare'},
    const {'1': 'search_rank_lost_absolute_top_impression_share', '3': 90, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'searchRankLostAbsoluteTopImpressionShare'},
    const {'1': 'search_rank_lost_impression_share', '3': 51, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'searchRankLostImpressionShare'},
    const {'1': 'search_rank_lost_top_impression_share', '3': 91, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'searchRankLostTopImpressionShare'},
    const {'1': 'search_top_impression_share', '3': 92, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'searchTopImpressionShare'},
    const {'1': 'speed_score', '3': 107, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'speedScore'},
    const {'1': 'top_impression_percentage', '3': 93, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'topImpressionPercentage'},
    const {'1': 'valid_accelerated_mobile_pages_clicks_percentage', '3': 108, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'validAcceleratedMobilePagesClicksPercentage'},
    const {'1': 'value_per_all_conversions', '3': 52, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'valuePerAllConversions'},
    const {'1': 'value_per_conversion', '3': 53, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'valuePerConversion'},
    const {'1': 'value_per_current_model_attributed_conversion', '3': 94, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'valuePerCurrentModelAttributedConversion'},
    const {'1': 'video_quartile_100_rate', '3': 54, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'videoQuartile100Rate'},
    const {'1': 'video_quartile_25_rate', '3': 55, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'videoQuartile25Rate'},
    const {'1': 'video_quartile_50_rate', '3': 56, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'videoQuartile50Rate'},
    const {'1': 'video_quartile_75_rate', '3': 57, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'videoQuartile75Rate'},
    const {'1': 'video_view_rate', '3': 58, '4': 1, '5': 11, '6': '.google.protobuf.DoubleValue', '10': 'videoViewRate'},
    const {'1': 'video_views', '3': 59, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'videoViews'},
    const {'1': 'view_through_conversions', '3': 60, '4': 1, '5': 11, '6': '.google.protobuf.Int64Value', '10': 'viewThroughConversions'},
  ],
};

