///
//  Generated code. Do not modify.
//  source: google/ads/googleads/v1/errors/ad_error.proto
///
// ignore_for_file: camel_case_types,non_constant_identifier_names,library_prefixes,unused_import,unused_shown_name

const AdErrorEnum$json = const {
  '1': 'AdErrorEnum',
  '4': const [AdErrorEnum_AdError$json],
};

const AdErrorEnum_AdError$json = const {
  '1': 'AdError',
  '2': const [
    const {'1': 'UNSPECIFIED', '2': 0},
    const {'1': 'UNKNOWN', '2': 1},
    const {'1': 'AD_CUSTOMIZERS_NOT_SUPPORTED_FOR_AD_TYPE', '2': 2},
    const {'1': 'APPROXIMATELY_TOO_LONG', '2': 3},
    const {'1': 'APPROXIMATELY_TOO_SHORT', '2': 4},
    const {'1': 'BAD_SNIPPET', '2': 5},
    const {'1': 'CANNOT_MODIFY_AD', '2': 6},
    const {'1': 'CANNOT_SET_BUSINESS_NAME_IF_URL_SET', '2': 7},
    const {'1': 'CANNOT_SET_FIELD', '2': 8},
    const {'1': 'CANNOT_SET_FIELD_WITH_ORIGIN_AD_ID_SET', '2': 9},
    const {'1': 'CANNOT_SET_FIELD_WITH_AD_ID_SET_FOR_SHARING', '2': 10},
    const {'1': 'CANNOT_SET_ALLOW_FLEXIBLE_COLOR_FALSE', '2': 11},
    const {'1': 'CANNOT_SET_COLOR_CONTROL_WHEN_NATIVE_FORMAT_SETTING', '2': 12},
    const {'1': 'CANNOT_SET_URL', '2': 13},
    const {'1': 'CANNOT_SET_WITHOUT_FINAL_URLS', '2': 14},
    const {'1': 'CANNOT_SET_WITH_FINAL_URLS', '2': 15},
    const {'1': 'CANNOT_SET_WITH_URL_DATA', '2': 17},
    const {'1': 'CANNOT_USE_AD_SUBCLASS_FOR_OPERATOR', '2': 18},
    const {'1': 'CUSTOMER_NOT_APPROVED_MOBILEADS', '2': 19},
    const {'1': 'CUSTOMER_NOT_APPROVED_THIRDPARTY_ADS', '2': 20},
    const {'1': 'CUSTOMER_NOT_APPROVED_THIRDPARTY_REDIRECT_ADS', '2': 21},
    const {'1': 'CUSTOMER_NOT_ELIGIBLE', '2': 22},
    const {'1': 'CUSTOMER_NOT_ELIGIBLE_FOR_UPDATING_BEACON_URL', '2': 23},
    const {'1': 'DIMENSION_ALREADY_IN_UNION', '2': 24},
    const {'1': 'DIMENSION_MUST_BE_SET', '2': 25},
    const {'1': 'DIMENSION_NOT_IN_UNION', '2': 26},
    const {'1': 'DISPLAY_URL_CANNOT_BE_SPECIFIED', '2': 27},
    const {'1': 'DOMESTIC_PHONE_NUMBER_FORMAT', '2': 28},
    const {'1': 'EMERGENCY_PHONE_NUMBER', '2': 29},
    const {'1': 'EMPTY_FIELD', '2': 30},
    const {'1': 'FEED_ATTRIBUTE_MUST_HAVE_MAPPING_FOR_TYPE_ID', '2': 31},
    const {'1': 'FEED_ATTRIBUTE_MAPPING_TYPE_MISMATCH', '2': 32},
    const {'1': 'ILLEGAL_AD_CUSTOMIZER_TAG_USE', '2': 33},
    const {'1': 'ILLEGAL_TAG_USE', '2': 34},
    const {'1': 'INCONSISTENT_DIMENSIONS', '2': 35},
    const {'1': 'INCONSISTENT_STATUS_IN_TEMPLATE_UNION', '2': 36},
    const {'1': 'INCORRECT_LENGTH', '2': 37},
    const {'1': 'INELIGIBLE_FOR_UPGRADE', '2': 38},
    const {'1': 'INVALID_AD_ADDRESS_CAMPAIGN_TARGET', '2': 39},
    const {'1': 'INVALID_AD_TYPE', '2': 40},
    const {'1': 'INVALID_ATTRIBUTES_FOR_MOBILE_IMAGE', '2': 41},
    const {'1': 'INVALID_ATTRIBUTES_FOR_MOBILE_TEXT', '2': 42},
    const {'1': 'INVALID_CALL_TO_ACTION_TEXT', '2': 43},
    const {'1': 'INVALID_CHARACTER_FOR_URL', '2': 44},
    const {'1': 'INVALID_COUNTRY_CODE', '2': 45},
    const {'1': 'INVALID_EXPANDED_DYNAMIC_SEARCH_AD_TAG', '2': 47},
    const {'1': 'INVALID_INPUT', '2': 48},
    const {'1': 'INVALID_MARKUP_LANGUAGE', '2': 49},
    const {'1': 'INVALID_MOBILE_CARRIER', '2': 50},
    const {'1': 'INVALID_MOBILE_CARRIER_TARGET', '2': 51},
    const {'1': 'INVALID_NUMBER_OF_ELEMENTS', '2': 52},
    const {'1': 'INVALID_PHONE_NUMBER_FORMAT', '2': 53},
    const {'1': 'INVALID_RICH_MEDIA_CERTIFIED_VENDOR_FORMAT_ID', '2': 54},
    const {'1': 'INVALID_TEMPLATE_DATA', '2': 55},
    const {'1': 'INVALID_TEMPLATE_ELEMENT_FIELD_TYPE', '2': 56},
    const {'1': 'INVALID_TEMPLATE_ID', '2': 57},
    const {'1': 'LINE_TOO_WIDE', '2': 58},
    const {'1': 'MISSING_AD_CUSTOMIZER_MAPPING', '2': 59},
    const {'1': 'MISSING_ADDRESS_COMPONENT', '2': 60},
    const {'1': 'MISSING_ADVERTISEMENT_NAME', '2': 61},
    const {'1': 'MISSING_BUSINESS_NAME', '2': 62},
    const {'1': 'MISSING_DESCRIPTION1', '2': 63},
    const {'1': 'MISSING_DESCRIPTION2', '2': 64},
    const {'1': 'MISSING_DESTINATION_URL_TAG', '2': 65},
    const {'1': 'MISSING_LANDING_PAGE_URL_TAG', '2': 66},
    const {'1': 'MISSING_DIMENSION', '2': 67},
    const {'1': 'MISSING_DISPLAY_URL', '2': 68},
    const {'1': 'MISSING_HEADLINE', '2': 69},
    const {'1': 'MISSING_HEIGHT', '2': 70},
    const {'1': 'MISSING_IMAGE', '2': 71},
    const {'1': 'MISSING_MARKETING_IMAGE_OR_PRODUCT_VIDEOS', '2': 72},
    const {'1': 'MISSING_MARKUP_LANGUAGES', '2': 73},
    const {'1': 'MISSING_MOBILE_CARRIER', '2': 74},
    const {'1': 'MISSING_PHONE', '2': 75},
    const {'1': 'MISSING_REQUIRED_TEMPLATE_FIELDS', '2': 76},
    const {'1': 'MISSING_TEMPLATE_FIELD_VALUE', '2': 77},
    const {'1': 'MISSING_TEXT', '2': 78},
    const {'1': 'MISSING_VISIBLE_URL', '2': 79},
    const {'1': 'MISSING_WIDTH', '2': 80},
    const {'1': 'MULTIPLE_DISTINCT_FEEDS_UNSUPPORTED', '2': 81},
    const {'1': 'MUST_USE_TEMP_AD_UNION_ID_ON_ADD', '2': 82},
    const {'1': 'TOO_LONG', '2': 83},
    const {'1': 'TOO_SHORT', '2': 84},
    const {'1': 'UNION_DIMENSIONS_CANNOT_CHANGE', '2': 85},
    const {'1': 'UNKNOWN_ADDRESS_COMPONENT', '2': 86},
    const {'1': 'UNKNOWN_FIELD_NAME', '2': 87},
    const {'1': 'UNKNOWN_UNIQUE_NAME', '2': 88},
    const {'1': 'UNSUPPORTED_DIMENSIONS', '2': 89},
    const {'1': 'URL_INVALID_SCHEME', '2': 90},
    const {'1': 'URL_INVALID_TOP_LEVEL_DOMAIN', '2': 91},
    const {'1': 'URL_MALFORMED', '2': 92},
    const {'1': 'URL_NO_HOST', '2': 93},
    const {'1': 'URL_NOT_EQUIVALENT', '2': 94},
    const {'1': 'URL_HOST_NAME_TOO_LONG', '2': 95},
    const {'1': 'URL_NO_SCHEME', '2': 96},
    const {'1': 'URL_NO_TOP_LEVEL_DOMAIN', '2': 97},
    const {'1': 'URL_PATH_NOT_ALLOWED', '2': 98},
    const {'1': 'URL_PORT_NOT_ALLOWED', '2': 99},
    const {'1': 'URL_QUERY_NOT_ALLOWED', '2': 100},
    const {'1': 'URL_SCHEME_BEFORE_EXPANDED_DYNAMIC_SEARCH_AD_TAG', '2': 102},
    const {'1': 'USER_DOES_NOT_HAVE_ACCESS_TO_TEMPLATE', '2': 103},
    const {'1': 'INCONSISTENT_EXPANDABLE_SETTINGS', '2': 104},
    const {'1': 'INVALID_FORMAT', '2': 105},
    const {'1': 'INVALID_FIELD_TEXT', '2': 106},
    const {'1': 'ELEMENT_NOT_PRESENT', '2': 107},
    const {'1': 'IMAGE_ERROR', '2': 108},
    const {'1': 'VALUE_NOT_IN_RANGE', '2': 109},
    const {'1': 'FIELD_NOT_PRESENT', '2': 110},
    const {'1': 'ADDRESS_NOT_COMPLETE', '2': 111},
    const {'1': 'ADDRESS_INVALID', '2': 112},
    const {'1': 'VIDEO_RETRIEVAL_ERROR', '2': 113},
    const {'1': 'AUDIO_ERROR', '2': 114},
    const {'1': 'INVALID_YOUTUBE_DISPLAY_URL', '2': 115},
    const {'1': 'TOO_MANY_PRODUCT_IMAGES', '2': 116},
    const {'1': 'TOO_MANY_PRODUCT_VIDEOS', '2': 117},
    const {'1': 'INCOMPATIBLE_AD_TYPE_AND_DEVICE_PREFERENCE', '2': 118},
    const {'1': 'CALLTRACKING_NOT_SUPPORTED_FOR_COUNTRY', '2': 119},
    const {'1': 'CARRIER_SPECIFIC_SHORT_NUMBER_NOT_ALLOWED', '2': 120},
    const {'1': 'DISALLOWED_NUMBER_TYPE', '2': 121},
    const {'1': 'PHONE_NUMBER_NOT_SUPPORTED_FOR_COUNTRY', '2': 122},
    const {'1': 'PHONE_NUMBER_NOT_SUPPORTED_WITH_CALLTRACKING_FOR_COUNTRY', '2': 123},
    const {'1': 'PREMIUM_RATE_NUMBER_NOT_ALLOWED', '2': 124},
    const {'1': 'VANITY_PHONE_NUMBER_NOT_ALLOWED', '2': 125},
    const {'1': 'INVALID_CALL_CONVERSION_TYPE_ID', '2': 126},
    const {'1': 'CANNOT_DISABLE_CALL_CONVERSION_AND_SET_CONVERSION_TYPE_ID', '2': 127},
    const {'1': 'CANNOT_SET_PATH2_WITHOUT_PATH1', '2': 128},
    const {'1': 'MISSING_DYNAMIC_SEARCH_ADS_SETTING_DOMAIN_NAME', '2': 129},
    const {'1': 'INCOMPATIBLE_WITH_RESTRICTION_TYPE', '2': 130},
    const {'1': 'CUSTOMER_CONSENT_FOR_CALL_RECORDING_REQUIRED', '2': 131},
    const {'1': 'MISSING_IMAGE_OR_MEDIA_BUNDLE', '2': 132},
    const {'1': 'PRODUCT_TYPE_NOT_SUPPORTED_IN_THIS_CAMPAIGN', '2': 133},
  ],
};

