///
//  Generated code. Do not modify.
//  source: google/ads/googleads/v1/errors/feed_item_validation_error.proto
///
// ignore_for_file: camel_case_types,non_constant_identifier_names,library_prefixes,unused_import,unused_shown_name

const FeedItemValidationErrorEnum$json = const {
  '1': 'FeedItemValidationErrorEnum',
  '4': const [FeedItemValidationErrorEnum_FeedItemValidationError$json],
};

const FeedItemValidationErrorEnum_FeedItemValidationError$json = const {
  '1': 'FeedItemValidationError',
  '2': const [
    const {'1': 'UNSPECIFIED', '2': 0},
    const {'1': 'UNKNOWN', '2': 1},
    const {'1': 'STRING_TOO_SHORT', '2': 2},
    const {'1': 'STRING_TOO_LONG', '2': 3},
    const {'1': 'VALUE_NOT_SPECIFIED', '2': 4},
    const {'1': 'INVALID_DOMESTIC_PHONE_NUMBER_FORMAT', '2': 5},
    const {'1': 'INVALID_PHONE_NUMBER', '2': 6},
    const {'1': 'PHONE_NUMBER_NOT_SUPPORTED_FOR_COUNTRY', '2': 7},
    const {'1': 'PREMIUM_RATE_NUMBER_NOT_ALLOWED', '2': 8},
    const {'1': 'DISALLOWED_NUMBER_TYPE', '2': 9},
    const {'1': 'VALUE_OUT_OF_RANGE', '2': 10},
    const {'1': 'CALLTRACKING_NOT_SUPPORTED_FOR_COUNTRY', '2': 11},
    const {'1': 'CUSTOMER_NOT_WHITELISTED_FOR_CALLTRACKING', '2': 12},
    const {'1': 'INVALID_COUNTRY_CODE', '2': 13},
    const {'1': 'INVALID_APP_ID', '2': 14},
    const {'1': 'MISSING_ATTRIBUTES_FOR_FIELDS', '2': 15},
    const {'1': 'INVALID_TYPE_ID', '2': 16},
    const {'1': 'INVALID_EMAIL_ADDRESS', '2': 17},
    const {'1': 'INVALID_HTTPS_URL', '2': 18},
    const {'1': 'MISSING_DELIVERY_ADDRESS', '2': 19},
    const {'1': 'START_DATE_AFTER_END_DATE', '2': 20},
    const {'1': 'MISSING_FEED_ITEM_START_TIME', '2': 21},
    const {'1': 'MISSING_FEED_ITEM_END_TIME', '2': 22},
    const {'1': 'MISSING_FEED_ITEM_ID', '2': 23},
    const {'1': 'VANITY_PHONE_NUMBER_NOT_ALLOWED', '2': 24},
    const {'1': 'INVALID_REVIEW_EXTENSION_SNIPPET', '2': 25},
    const {'1': 'INVALID_NUMBER_FORMAT', '2': 26},
    const {'1': 'INVALID_DATE_FORMAT', '2': 27},
    const {'1': 'INVALID_PRICE_FORMAT', '2': 28},
    const {'1': 'UNKNOWN_PLACEHOLDER_FIELD', '2': 29},
    const {'1': 'MISSING_ENHANCED_SITELINK_DESCRIPTION_LINE', '2': 30},
    const {'1': 'REVIEW_EXTENSION_SOURCE_INELIGIBLE', '2': 31},
    const {'1': 'HYPHENS_IN_REVIEW_EXTENSION_SNIPPET', '2': 32},
    const {'1': 'DOUBLE_QUOTES_IN_REVIEW_EXTENSION_SNIPPET', '2': 33},
    const {'1': 'QUOTES_IN_REVIEW_EXTENSION_SNIPPET', '2': 34},
    const {'1': 'INVALID_FORM_ENCODED_PARAMS', '2': 35},
    const {'1': 'INVALID_URL_PARAMETER_NAME', '2': 36},
    const {'1': 'NO_GEOCODING_RESULT', '2': 37},
    const {'1': 'SOURCE_NAME_IN_REVIEW_EXTENSION_TEXT', '2': 38},
    const {'1': 'CARRIER_SPECIFIC_SHORT_NUMBER_NOT_ALLOWED', '2': 39},
    const {'1': 'INVALID_PLACEHOLDER_FIELD_ID', '2': 40},
    const {'1': 'INVALID_URL_TAG', '2': 41},
    const {'1': 'LIST_TOO_LONG', '2': 42},
    const {'1': 'INVALID_ATTRIBUTES_COMBINATION', '2': 43},
    const {'1': 'DUPLICATE_VALUES', '2': 44},
    const {'1': 'INVALID_CALL_CONVERSION_ACTION_ID', '2': 45},
    const {'1': 'CANNOT_SET_WITHOUT_FINAL_URLS', '2': 46},
    const {'1': 'APP_ID_DOESNT_EXIST_IN_APP_STORE', '2': 47},
    const {'1': 'INVALID_FINAL_URL', '2': 48},
    const {'1': 'INVALID_TRACKING_URL', '2': 49},
    const {'1': 'INVALID_FINAL_URL_FOR_APP_DOWNLOAD_URL', '2': 50},
    const {'1': 'LIST_TOO_SHORT', '2': 51},
    const {'1': 'INVALID_USER_ACTION', '2': 52},
    const {'1': 'INVALID_TYPE_NAME', '2': 53},
    const {'1': 'INVALID_EVENT_CHANGE_STATUS', '2': 54},
    const {'1': 'INVALID_SNIPPETS_HEADER', '2': 55},
    const {'1': 'INVALID_ANDROID_APP_LINK', '2': 56},
    const {'1': 'NUMBER_TYPE_WITH_CALLTRACKING_NOT_SUPPORTED_FOR_COUNTRY', '2': 57},
    const {'1': 'RESERVED_KEYWORD_OTHER', '2': 58},
    const {'1': 'DUPLICATE_OPTION_LABELS', '2': 59},
    const {'1': 'DUPLICATE_OPTION_PREFILLS', '2': 60},
    const {'1': 'UNEQUAL_LIST_LENGTHS', '2': 61},
    const {'1': 'INCONSISTENT_CURRENCY_CODES', '2': 62},
    const {'1': 'PRICE_EXTENSION_HAS_DUPLICATED_HEADERS', '2': 63},
    const {'1': 'ITEM_HAS_DUPLICATED_HEADER_AND_DESCRIPTION', '2': 64},
    const {'1': 'PRICE_EXTENSION_HAS_TOO_FEW_ITEMS', '2': 65},
    const {'1': 'UNSUPPORTED_VALUE', '2': 66},
    const {'1': 'INVALID_FINAL_MOBILE_URL', '2': 67},
    const {'1': 'INVALID_KEYWORDLESS_AD_RULE_LABEL', '2': 68},
    const {'1': 'VALUE_TRACK_PARAMETER_NOT_SUPPORTED', '2': 69},
    const {'1': 'UNSUPPORTED_VALUE_IN_SELECTED_LANGUAGE', '2': 70},
    const {'1': 'INVALID_IOS_APP_LINK', '2': 71},
    const {'1': 'MISSING_IOS_APP_LINK_OR_IOS_APP_STORE_ID', '2': 72},
    const {'1': 'PROMOTION_INVALID_TIME', '2': 73},
    const {'1': 'PROMOTION_CANNOT_SET_PERCENT_OFF_AND_MONEY_AMOUNT_OFF', '2': 74},
    const {'1': 'PROMOTION_CANNOT_SET_PROMOTION_CODE_AND_ORDERS_OVER_AMOUNT', '2': 75},
    const {'1': 'TOO_MANY_DECIMAL_PLACES_SPECIFIED', '2': 76},
    const {'1': 'AD_CUSTOMIZERS_NOT_ALLOWED', '2': 77},
    const {'1': 'INVALID_LANGUAGE_CODE', '2': 78},
    const {'1': 'UNSUPPORTED_LANGUAGE', '2': 79},
    const {'1': 'IF_FUNCTION_NOT_ALLOWED', '2': 80},
    const {'1': 'INVALID_FINAL_URL_SUFFIX', '2': 81},
    const {'1': 'INVALID_TAG_IN_FINAL_URL_SUFFIX', '2': 82},
    const {'1': 'INVALID_FINAL_URL_SUFFIX_FORMAT', '2': 83},
    const {'1': 'CUSTOMER_CONSENT_FOR_CALL_RECORDING_REQUIRED', '2': 84},
    const {'1': 'ONLY_ONE_DELIVERY_OPTION_IS_ALLOWED', '2': 85},
    const {'1': 'NO_DELIVERY_OPTION_IS_SET', '2': 86},
    const {'1': 'INVALID_CONVERSION_REPORTING_STATE', '2': 87},
    const {'1': 'IMAGE_SIZE_WRONG', '2': 88},
    const {'1': 'EMAIL_DELIVERY_NOT_AVAILABLE_IN_COUNTRY', '2': 89},
    const {'1': 'AUTO_REPLY_NOT_AVAILABLE_IN_COUNTRY', '2': 90},
    const {'1': 'INVALID_LATITUDE_VALUE', '2': 91},
    const {'1': 'INVALID_LONGITUDE_VALUE', '2': 92},
    const {'1': 'TOO_MANY_LABELS', '2': 93},
    const {'1': 'INVALID_IMAGE_URL', '2': 94},
    const {'1': 'MISSING_LATITUDE_VALUE', '2': 95},
    const {'1': 'MISSING_LONGITUDE_VALUE', '2': 96},
  ],
};

