///
//  Generated code. Do not modify.
//  source: google/ads/googleads/v1/errors/query_error.proto
///
// ignore_for_file: camel_case_types,non_constant_identifier_names,library_prefixes,unused_import,unused_shown_name

const QueryErrorEnum$json = const {
  '1': 'QueryErrorEnum',
  '4': const [QueryErrorEnum_QueryError$json],
};

const QueryErrorEnum_QueryError$json = const {
  '1': 'QueryError',
  '2': const [
    const {'1': 'UNSPECIFIED', '2': 0},
    const {'1': 'UNKNOWN', '2': 1},
    const {'1': 'QUERY_ERROR', '2': 50},
    const {'1': 'BAD_ENUM_CONSTANT', '2': 18},
    const {'1': 'BAD_ESCAPE_SEQUENCE', '2': 7},
    const {'1': 'BAD_FIELD_NAME', '2': 12},
    const {'1': 'BAD_LIMIT_VALUE', '2': 15},
    const {'1': 'BAD_NUMBER', '2': 5},
    const {'1': 'BAD_OPERATOR', '2': 3},
    const {'1': 'BAD_PARAMETER_NAME', '2': 61},
    const {'1': 'BAD_PARAMETER_VALUE', '2': 62},
    const {'1': 'BAD_RESOURCE_TYPE_IN_FROM_CLAUSE', '2': 45},
    const {'1': 'BAD_SYMBOL', '2': 2},
    const {'1': 'BAD_VALUE', '2': 4},
    const {'1': 'DATE_RANGE_TOO_WIDE', '2': 36},
    const {'1': 'EXPECTED_AND', '2': 30},
    const {'1': 'EXPECTED_BY', '2': 14},
    const {'1': 'EXPECTED_DIMENSION_FIELD_IN_SELECT_CLAUSE', '2': 37},
    const {'1': 'EXPECTED_FILTERS_ON_DATE_RANGE', '2': 55},
    const {'1': 'EXPECTED_FROM', '2': 44},
    const {'1': 'EXPECTED_LIST', '2': 41},
    const {'1': 'EXPECTED_REFERENCED_FIELD_IN_SELECT_CLAUSE', '2': 16},
    const {'1': 'EXPECTED_SELECT', '2': 13},
    const {'1': 'EXPECTED_SINGLE_VALUE', '2': 42},
    const {'1': 'EXPECTED_VALUE_WITH_BETWEEN_OPERATOR', '2': 29},
    const {'1': 'INVALID_DATE_FORMAT', '2': 38},
    const {'1': 'INVALID_STRING_VALUE', '2': 57},
    const {'1': 'INVALID_VALUE_WITH_BETWEEN_OPERATOR', '2': 26},
    const {'1': 'INVALID_VALUE_WITH_DURING_OPERATOR', '2': 22},
    const {'1': 'INVALID_VALUE_WITH_LIKE_OPERATOR', '2': 56},
    const {'1': 'OPERATOR_FIELD_MISMATCH', '2': 35},
    const {'1': 'PROHIBITED_EMPTY_LIST_IN_CONDITION', '2': 28},
    const {'1': 'PROHIBITED_ENUM_CONSTANT', '2': 54},
    const {'1': 'PROHIBITED_FIELD_COMBINATION_IN_SELECT_CLAUSE', '2': 31},
    const {'1': 'PROHIBITED_FIELD_IN_ORDER_BY_CLAUSE', '2': 40},
    const {'1': 'PROHIBITED_FIELD_IN_SELECT_CLAUSE', '2': 23},
    const {'1': 'PROHIBITED_FIELD_IN_WHERE_CLAUSE', '2': 24},
    const {'1': 'PROHIBITED_RESOURCE_TYPE_IN_FROM_CLAUSE', '2': 43},
    const {'1': 'PROHIBITED_RESOURCE_TYPE_IN_SELECT_CLAUSE', '2': 48},
    const {'1': 'PROHIBITED_RESOURCE_TYPE_IN_WHERE_CLAUSE', '2': 58},
    const {'1': 'PROHIBITED_METRIC_IN_SELECT_OR_WHERE_CLAUSE', '2': 49},
    const {'1': 'PROHIBITED_SEGMENT_IN_SELECT_OR_WHERE_CLAUSE', '2': 51},
    const {'1': 'PROHIBITED_SEGMENT_WITH_METRIC_IN_SELECT_OR_WHERE_CLAUSE', '2': 53},
    const {'1': 'LIMIT_VALUE_TOO_LOW', '2': 25},
    const {'1': 'PROHIBITED_NEWLINE_IN_STRING', '2': 8},
    const {'1': 'PROHIBITED_VALUE_COMBINATION_IN_LIST', '2': 10},
    const {'1': 'PROHIBITED_VALUE_COMBINATION_WITH_BETWEEN_OPERATOR', '2': 21},
    const {'1': 'STRING_NOT_TERMINATED', '2': 6},
    const {'1': 'TOO_MANY_SEGMENTS', '2': 34},
    const {'1': 'UNEXPECTED_END_OF_QUERY', '2': 9},
    const {'1': 'UNEXPECTED_FROM_CLAUSE', '2': 47},
    const {'1': 'UNRECOGNIZED_FIELD', '2': 32},
    const {'1': 'UNEXPECTED_INPUT', '2': 11},
    const {'1': 'REQUESTED_METRICS_FOR_MANAGER', '2': 59},
  ],
};

