///
//  Generated code. Do not modify.
//  source: google/ads/googleads/v1/errors/url_field_error.proto
///
// ignore_for_file: camel_case_types,non_constant_identifier_names,library_prefixes,unused_import,unused_shown_name

const UrlFieldErrorEnum$json = {
  '1': 'UrlFieldErrorEnum',
  '4': [UrlFieldErrorEnum_UrlFieldError$json],
};

const UrlFieldErrorEnum_UrlFieldError$json = {
  '1': 'UrlFieldError',
  '2': [
    {'1': 'UNSPECIFIED', '2': 0},
    {'1': 'UNKNOWN', '2': 1},
    {'1': 'INVALID_TRACKING_URL_TEMPLATE', '2': 2},
    {'1': 'INVALID_TAG_IN_TRACKING_URL_TEMPLATE', '2': 3},
    {'1': 'MISSING_TRACKING_URL_TEMPLATE_TAG', '2': 4},
    {'1': 'MISSING_PROTOCOL_IN_TRACKING_URL_TEMPLATE', '2': 5},
    {'1': 'INVALID_PROTOCOL_IN_TRACKING_URL_TEMPLATE', '2': 6},
    {'1': 'MALFORMED_TRACKING_URL_TEMPLATE', '2': 7},
    {'1': 'MISSING_HOST_IN_TRACKING_URL_TEMPLATE', '2': 8},
    {'1': 'INVALID_TLD_IN_TRACKING_URL_TEMPLATE', '2': 9},
    {'1': 'REDUNDANT_NESTED_TRACKING_URL_TEMPLATE_TAG', '2': 10},
    {'1': 'INVALID_FINAL_URL', '2': 11},
    {'1': 'INVALID_TAG_IN_FINAL_URL', '2': 12},
    {'1': 'REDUNDANT_NESTED_FINAL_URL_TAG', '2': 13},
    {'1': 'MISSING_PROTOCOL_IN_FINAL_URL', '2': 14},
    {'1': 'INVALID_PROTOCOL_IN_FINAL_URL', '2': 15},
    {'1': 'MALFORMED_FINAL_URL', '2': 16},
    {'1': 'MISSING_HOST_IN_FINAL_URL', '2': 17},
    {'1': 'INVALID_TLD_IN_FINAL_URL', '2': 18},
    {'1': 'INVALID_FINAL_MOBILE_URL', '2': 19},
    {'1': 'INVALID_TAG_IN_FINAL_MOBILE_URL', '2': 20},
    {'1': 'REDUNDANT_NESTED_FINAL_MOBILE_URL_TAG', '2': 21},
    {'1': 'MISSING_PROTOCOL_IN_FINAL_MOBILE_URL', '2': 22},
    {'1': 'INVALID_PROTOCOL_IN_FINAL_MOBILE_URL', '2': 23},
    {'1': 'MALFORMED_FINAL_MOBILE_URL', '2': 24},
    {'1': 'MISSING_HOST_IN_FINAL_MOBILE_URL', '2': 25},
    {'1': 'INVALID_TLD_IN_FINAL_MOBILE_URL', '2': 26},
    {'1': 'INVALID_FINAL_APP_URL', '2': 27},
    {'1': 'INVALID_TAG_IN_FINAL_APP_URL', '2': 28},
    {'1': 'REDUNDANT_NESTED_FINAL_APP_URL_TAG', '2': 29},
    {'1': 'MULTIPLE_APP_URLS_FOR_OSTYPE', '2': 30},
    {'1': 'INVALID_OSTYPE', '2': 31},
    {'1': 'INVALID_PROTOCOL_FOR_APP_URL', '2': 32},
    {'1': 'INVALID_PACKAGE_ID_FOR_APP_URL', '2': 33},
    {'1': 'URL_CUSTOM_PARAMETERS_COUNT_EXCEEDS_LIMIT', '2': 34},
    {'1': 'INVALID_CHARACTERS_IN_URL_CUSTOM_PARAMETER_KEY', '2': 39},
    {'1': 'INVALID_CHARACTERS_IN_URL_CUSTOM_PARAMETER_VALUE', '2': 40},
    {'1': 'INVALID_TAG_IN_URL_CUSTOM_PARAMETER_VALUE', '2': 41},
    {'1': 'REDUNDANT_NESTED_URL_CUSTOM_PARAMETER_TAG', '2': 42},
    {'1': 'MISSING_PROTOCOL', '2': 43},
    {'1': 'INVALID_PROTOCOL', '2': 52},
    {'1': 'INVALID_URL', '2': 44},
    {'1': 'DESTINATION_URL_DEPRECATED', '2': 45},
    {'1': 'INVALID_TAG_IN_URL', '2': 46},
    {'1': 'MISSING_URL_TAG', '2': 47},
    {'1': 'DUPLICATE_URL_ID', '2': 48},
    {'1': 'INVALID_URL_ID', '2': 49},
    {'1': 'FINAL_URL_SUFFIX_MALFORMED', '2': 50},
    {'1': 'INVALID_TAG_IN_FINAL_URL_SUFFIX', '2': 51},
    {'1': 'INVALID_TOP_LEVEL_DOMAIN', '2': 53},
    {'1': 'MALFORMED_TOP_LEVEL_DOMAIN', '2': 54},
    {'1': 'MALFORMED_URL', '2': 55},
    {'1': 'MISSING_HOST', '2': 56},
  ],
};
