///
//  Generated code. Do not modify.
//  source: google/ads/googleads/v2/enums/click_type.proto
//
// @dart = 2.3
// ignore_for_file: camel_case_types,non_constant_identifier_names,library_prefixes,unused_import,unused_shown_name,return_of_invalid_type

const ClickTypeEnum$json = {
  '1': 'ClickTypeEnum',
  '4': [ClickTypeEnum_ClickType$json],
};

const ClickTypeEnum_ClickType$json = {
  '1': 'ClickType',
  '2': [
    {'1': 'UNSPECIFIED', '2': 0},
    {'1': 'UNKNOWN', '2': 1},
    {'1': 'APP_DEEPLINK', '2': 2},
    {'1': 'BREADCRUMBS', '2': 3},
    {'1': 'BROADBAND_PLAN', '2': 4},
    {'1': 'CALL_TRACKING', '2': 5},
    {'1': 'CALLS', '2': 6},
    {'1': 'CLICK_ON_ENGAGEMENT_AD', '2': 7},
    {'1': 'GET_DIRECTIONS', '2': 8},
    {'1': 'LOCATION_EXPANSION', '2': 9},
    {'1': 'LOCATION_FORMAT_CALL', '2': 10},
    {'1': 'LOCATION_FORMAT_DIRECTIONS', '2': 11},
    {'1': 'LOCATION_FORMAT_IMAGE', '2': 12},
    {'1': 'LOCATION_FORMAT_LANDING_PAGE', '2': 13},
    {'1': 'LOCATION_FORMAT_MAP', '2': 14},
    {'1': 'LOCATION_FORMAT_STORE_INFO', '2': 15},
    {'1': 'LOCATION_FORMAT_TEXT', '2': 16},
    {'1': 'MOBILE_CALL_TRACKING', '2': 17},
    {'1': 'OFFER_PRINTS', '2': 18},
    {'1': 'OTHER', '2': 19},
    {'1': 'PRODUCT_EXTENSION_CLICKS', '2': 20},
    {'1': 'PRODUCT_LISTING_AD_CLICKS', '2': 21},
    {'1': 'SITELINKS', '2': 22},
    {'1': 'STORE_LOCATOR', '2': 23},
    {'1': 'URL_CLICKS', '2': 25},
    {'1': 'VIDEO_APP_STORE_CLICKS', '2': 26},
    {'1': 'VIDEO_CALL_TO_ACTION_CLICKS', '2': 27},
    {'1': 'VIDEO_CARD_ACTION_HEADLINE_CLICKS', '2': 28},
    {'1': 'VIDEO_END_CAP_CLICKS', '2': 29},
    {'1': 'VIDEO_WEBSITE_CLICKS', '2': 30},
    {'1': 'VISUAL_SITELINKS', '2': 31},
    {'1': 'WIRELESS_PLAN', '2': 32},
    {'1': 'PRODUCT_LISTING_AD_LOCAL', '2': 33},
    {'1': 'PRODUCT_LISTING_AD_MULTICHANNEL_LOCAL', '2': 34},
    {'1': 'PRODUCT_LISTING_AD_MULTICHANNEL_ONLINE', '2': 35},
    {'1': 'PRODUCT_LISTING_ADS_COUPON', '2': 36},
    {'1': 'PRODUCT_LISTING_AD_TRANSACTABLE', '2': 37},
    {'1': 'PRODUCT_AD_APP_DEEPLINK', '2': 38},
    {'1': 'SHOWCASE_AD_CATEGORY_LINK', '2': 39},
    {'1': 'SHOWCASE_AD_LOCAL_STOREFRONT_LINK', '2': 40},
    {'1': 'SHOWCASE_AD_ONLINE_PRODUCT_LINK', '2': 42},
    {'1': 'SHOWCASE_AD_LOCAL_PRODUCT_LINK', '2': 43},
    {'1': 'PROMOTION_EXTENSION', '2': 44},
    {'1': 'SWIPEABLE_GALLERY_AD_HEADLINE', '2': 45},
    {'1': 'SWIPEABLE_GALLERY_AD_SWIPES', '2': 46},
    {'1': 'SWIPEABLE_GALLERY_AD_SEE_MORE', '2': 47},
    {'1': 'SWIPEABLE_GALLERY_AD_SITELINK_ONE', '2': 48},
    {'1': 'SWIPEABLE_GALLERY_AD_SITELINK_TWO', '2': 49},
    {'1': 'SWIPEABLE_GALLERY_AD_SITELINK_THREE', '2': 50},
    {'1': 'SWIPEABLE_GALLERY_AD_SITELINK_FOUR', '2': 51},
    {'1': 'SWIPEABLE_GALLERY_AD_SITELINK_FIVE', '2': 52},
    {'1': 'HOTEL_PRICE', '2': 53},
    {'1': 'PRICE_EXTENSION', '2': 54},
    {'1': 'HOTEL_BOOK_ON_GOOGLE_ROOM_SELECTION', '2': 55},
    {'1': 'SHOPPING_COMPARISON_LISTING', '2': 56},
  ],
};
